applications:
- name: app-of-apps-dev
  namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/fortranhub/qr-argo-cd-apps.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
